version: "3"
services:
  node:
    image: node:22-alpine
    container_name: node_app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
      - "3001:3001"
    expose:
      - "3001"
    depends_on:
      - mongo
    command: sh -c "npm install && npm start"

  mongo:
    image: mongo:6.0.7
